DROP TABLE IF EXISTS seckill_order;
DROP TABLE IF EXISTS seckill_product;

CREATE TABLE seckill_product (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    stock INT NOT NULL,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE seckill_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    mode VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_order_product ON seckill_order(product_id);

