drop table if exists audit_log;
drop table if exists review_task;
drop table if exists notification;
drop table if exists book_borrow;
drop table if exists book;
drop table if exists device;
drop table if exists room;
drop table if exists activity_registration;
drop table if exists activity;
drop table if exists campus_user;

create table campus_user (
    id bigint generated by default as identity primary key,
    username varchar(40) not null unique,
    display_name varchar(80) not null,
    role_code varchar(40) not null,
    password_hint varchar(40) not null,
    status varchar(20) not null,
    failed_login_count int not null default 0
);

create table activity (
    id bigint generated by default as identity primary key,
    title varchar(120) not null,
    organizer varchar(80) not null,
    location varchar(80) not null,
    capacity int not null,
    registered_count int not null default 0,
    status varchar(20) not null
);

create table activity_registration (
    id bigint generated by default as identity primary key,
    activity_id bigint not null,
    user_id bigint not null,
    status varchar(20) not null,
    created_at timestamp not null
);

create table room (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    building varchar(80) not null,
    capacity int not null,
    status varchar(20) not null
);

create table device (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    category varchar(40) not null,
    total_quantity int not null,
    available_quantity int not null,
    status varchar(20) not null
);

create table book (
    id bigint generated by default as identity primary key,
    isbn varchar(30) not null unique,
    title varchar(120) not null,
    author varchar(80) not null,
    category varchar(60) not null,
    total_copies int not null,
    available_copies int not null
);

create table book_borrow (
    id bigint generated by default as identity primary key,
    book_id bigint not null,
    user_id bigint not null,
    status varchar(20) not null,
    borrowed_at date not null,
    due_at date not null,
    renew_count int not null default 0
);

create table notification (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(120) not null,
    read_flag boolean not null default false
);

create table review_task (
    id bigint generated by default as identity primary key,
    task_type varchar(40) not null,
    title varchar(120) not null,
    applicant varchar(40) not null,
    status varchar(20) not null,
    reviewer varchar(40),
    comment varchar(200),
    created_at timestamp not null,
    reviewed_at timestamp
);

create table audit_log (
    id bigint generated by default as identity primary key,
    actor varchar(40) not null,
    action varchar(80) not null,
    target_type varchar(40) not null,
    target_id bigint not null,
    created_at timestamp not null
);
